name: test
on:
        push:
                branches: [ main ]
jobs:
        build:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - run: python hello.py
                        - run: pip install -r requirements.txt
                        - run: pytest
